// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsScriptRunner.Infrastructure.Persistence;

#nullable disable

namespace WindowsScriptRunner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WindowsScriptRunnerDbContext))]
    [Migration("20260731165153_AddTrustedDryRunApprovalEvidence")]
    partial class AddTrustedDryRunApprovalEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wsr")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("JobLeaseFencingSequence", "wsr")
                .HasMin(1L);

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredUtc")
                        .HasDatabaseName("IX_AuditEvents_OccurredUtc");

                    b.HasIndex("Actor", "OccurredUtc")
                        .HasDatabaseName("IX_AuditEvents_Actor_OccurredUtc");

                    b.HasIndex("EventType", "OccurredUtc")
                        .HasDatabaseName("IX_AuditEvents_EventType_OccurredUtc");

                    b.HasIndex("EntityType", "EntityId", "OccurredUtc")
                        .HasDatabaseName("IX_AuditEvents_Entity_OccurredUtc");

                    b.ToTable("AuditEvents", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_AuditEvents_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.AuditEventPropertyEntity", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("AuditEventId", "NormalizedKey");

                    b.ToTable("AuditEventProperties", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_AuditEventProperties_NonSensitiveKey", "[NormalizedKey] NOT LIKE '%PASSWORD%' AND [NormalizedKey] NOT LIKE '%SECRET%' AND ([NormalizedKey] NOT LIKE '%TOKEN%' OR [NormalizedKey] = 'FENCINGTOKEN')");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.CredentialReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("ExternalIdentifierHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedProviderType", "ExternalIdentifierHash")
                        .IsUnique()
                        .HasDatabaseName("UX_CredentialReferences_Provider_ExternalHash");

                    b.ToTable("CredentialReferences", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_CredentialReferences_Hash", "DATALENGTH([ExternalIdentifierHash]) = 32");

                            t.HasCheckConstraint("CK_CredentialReferences_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobApprovalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalFingerprint")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("DecisionUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "DecisionUtc")
                        .HasDatabaseName("IX_JobApprovals_Job_DecisionUtc");

                    b.ToTable("JobApprovals", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_JobApprovals_Decision", "[Decision] IN ('Approved','Rejected')");

                            t.HasCheckConstraint("CK_JobApprovals_Fingerprint", "LEN([ApprovalFingerprint]) = 64 AND [ApprovalFingerprint] NOT LIKE '%[^0-9a-f]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_JobApprovals_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedDryRunEvidenceCompletedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long?>("AcceptedDryRunEvidenceFencingToken")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AcceptedDryRunEvidenceLeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptedDryRunEvidenceSource")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("AcceptedDryRunEvidenceWindowOpenedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AcceptedDryRunEvidenceWorkKind")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("AcceptedDryRunEvidenceWorkerNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LastActingUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PolicyRiskLevel")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("PolicyScriptDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyScriptVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("PolicySupportsExecute")
                        .HasColumnType("bit");

                    b.Property<bool?>("PolicySupportsPostValidation")
                        .HasColumnType("bit");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestedPhase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ScriptDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScriptVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("SubmittedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc")
                        .HasDatabaseName("IX_Jobs_CreatedUtc");

                    b.HasIndex("ScriptVersionId")
                        .HasDatabaseName("IX_Jobs_ScriptVersionId");

                    b.HasIndex("RequestedBy", "CreatedUtc")
                        .HasDatabaseName("IX_Jobs_RequestedBy_CreatedUtc");

                    b.HasIndex("ScriptDefinitionId", "ScriptVersionId")
                        .HasDatabaseName("IX_Jobs_ScriptDefinitionId_ScriptVersionId");

                    b.HasIndex("Status", "UpdatedUtc")
                        .HasDatabaseName("IX_Jobs_Status_UpdatedUtc");

                    b.ToTable("Jobs", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_Jobs_AcceptedDryRunEvidence", "([AcceptedDryRunEvidenceWorkKind] IS NULL AND [AcceptedDryRunEvidenceSource] IS NULL AND [AcceptedDryRunEvidenceWorkerNodeId] IS NULL AND [AcceptedDryRunEvidenceLeaseId] IS NULL AND [AcceptedDryRunEvidenceFencingToken] IS NULL AND [AcceptedDryRunEvidenceWindowOpenedUtc] IS NULL AND [AcceptedDryRunEvidenceCompletedUtc] IS NULL) OR ([AcceptedDryRunEvidenceWorkKind] IS NOT NULL AND [AcceptedDryRunEvidenceWorkKind] = 'DryRun' AND [AcceptedDryRunEvidenceSource] IS NOT NULL AND [AcceptedDryRunEvidenceSource] = 'InternalLifecycle' AND [AcceptedDryRunEvidenceWorkerNodeId] IS NULL AND [AcceptedDryRunEvidenceLeaseId] IS NULL AND [AcceptedDryRunEvidenceFencingToken] IS NULL AND [AcceptedDryRunEvidenceWindowOpenedUtc] IS NOT NULL AND [AcceptedDryRunEvidenceCompletedUtc] IS NOT NULL AND [AcceptedDryRunEvidenceWindowOpenedUtc] <= [AcceptedDryRunEvidenceCompletedUtc]) OR ([AcceptedDryRunEvidenceWorkKind] IS NOT NULL AND [AcceptedDryRunEvidenceWorkKind] = 'DryRun' AND [AcceptedDryRunEvidenceSource] IS NOT NULL AND [AcceptedDryRunEvidenceSource] = 'LeasedWorker' AND [AcceptedDryRunEvidenceWorkerNodeId] IS NOT NULL AND [AcceptedDryRunEvidenceWorkerNodeId] <> '00000000-0000-0000-0000-000000000000' AND [AcceptedDryRunEvidenceLeaseId] IS NOT NULL AND [AcceptedDryRunEvidenceLeaseId] <> '00000000-0000-0000-0000-000000000000' AND [AcceptedDryRunEvidenceFencingToken] IS NOT NULL AND [AcceptedDryRunEvidenceFencingToken] > 0 AND [AcceptedDryRunEvidenceWindowOpenedUtc] IS NOT NULL AND [AcceptedDryRunEvidenceCompletedUtc] IS NOT NULL AND [AcceptedDryRunEvidenceWindowOpenedUtc] <= [AcceptedDryRunEvidenceCompletedUtc])");

                            t.HasCheckConstraint("CK_Jobs_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Jobs_PolicyRiskLevel", "[PolicyRiskLevel] IS NULL OR [PolicyRiskLevel] IN ('ReadOnly','Low','Medium','High','Critical')");

                            t.HasCheckConstraint("CK_Jobs_PolicySnapshot_AllOrNone", "([PolicyScriptDefinitionId] IS NULL AND [PolicyScriptVersionId] IS NULL AND [PolicyRiskLevel] IS NULL AND [PolicySupportsExecute] IS NULL AND [PolicySupportsPostValidation] IS NULL AND [SubmittedUtc] IS NULL AND [Status] = 'Draft') OR ([PolicyScriptDefinitionId] IS NOT NULL AND [PolicyScriptVersionId] IS NOT NULL AND [PolicyRiskLevel] IS NOT NULL AND [PolicySupportsExecute] IS NOT NULL AND [PolicySupportsPostValidation] IS NOT NULL AND [SubmittedUtc] IS NOT NULL AND [Status] <> 'Draft')");

                            t.HasCheckConstraint("CK_Jobs_PolicySnapshot_Ids", "[PolicyScriptDefinitionId] IS NULL OR ([PolicyScriptDefinitionId] = [ScriptDefinitionId] AND [PolicyScriptVersionId] = [ScriptVersionId])");

                            t.HasCheckConstraint("CK_Jobs_RequestedPhase", "[RequestedPhase] IN ('Discovery','Validation','DryRun','Report','Execute','PostValidation')");

                            t.HasCheckConstraint("CK_Jobs_Status", "[Status] IN ('Draft','Submitted','Validated','DryRunQueued','DryRunRunning','DryRunCompleted','AwaitingApproval','Approved','ExecutionQueued','Claimed','Executing','PostValidation','Completed','CompletedWithWarnings','Failed','Rejected','Cancelled','TimedOut','Blocked','NotRun')");

                            t.HasCheckConstraint("CK_Jobs_Timestamps", "[CreatedUtc] <= [UpdatedUtc] AND ([SubmittedUtc] IS NULL OR ([SubmittedUtc] >= [CreatedUtc] AND [SubmittedUtc] <= [UpdatedUtc]))");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Outcome")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("WorkerNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("UX_JobExecutions_OneActivePerJob")
                        .HasFilter("[StartedUtc] IS NOT NULL AND [CompletedUtc] IS NULL");

                    b.HasIndex("WorkerNodeId");

                    b.HasIndex("JobId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_JobExecutions_Job_Attempt");

                    b.ToTable("JobExecutions", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_JobExecutions_Attempt", "[AttemptNumber] > 0");

                            t.HasCheckConstraint("CK_JobExecutions_Completion", "([CompletedUtc] IS NULL AND [Outcome] IS NULL AND [ExitCode] IS NULL AND [Summary] IS NULL) OR ([CompletedUtc] IS NOT NULL AND [StartedUtc] IS NOT NULL AND [CompletedUtc] >= [StartedUtc] AND [Outcome] IS NOT NULL)");

                            t.HasCheckConstraint("CK_JobExecutions_ExitCode", "[Outcome] IS NULL OR [ExitCode] IS NOT NULL OR [Outcome] IN ('Cancelled','TimedOut','Blocked','NotRun')");

                            t.HasCheckConstraint("CK_JobExecutions_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_JobExecutions_Outcome", "[Outcome] IS NULL OR [Outcome] IN ('Succeeded','SucceededWithWarnings','Failed','Cancelled','TimedOut','Blocked','NotRun')");

                            t.HasCheckConstraint("CK_JobExecutions_Start", "[StartedUtc] IS NULL OR [StartedUtc] >= [CreatedUtc]");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobLeaseEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcquiredUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("FencingToken")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastRenewedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("WorkKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("WorkerNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("IX_JobLeases_ExpiresUtc");

                    b.HasIndex("LeaseId")
                        .IsUnique()
                        .HasDatabaseName("UX_JobLeases_LeaseId");

                    b.HasIndex("WorkKind", "ExpiresUtc")
                        .HasDatabaseName("IX_JobLeases_WorkKind_ExpiresUtc");

                    b.HasIndex("WorkerNodeId", "ExpiresUtc")
                        .HasDatabaseName("IX_JobLeases_WorkerNodeId_ExpiresUtc");

                    b.ToTable("JobLeases", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_JobLeases_FencingToken", "[FencingToken] > 0");

                            t.HasCheckConstraint("CK_JobLeases_JobId", "[JobId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_JobLeases_LeaseId", "[LeaseId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_JobLeases_Timestamps", "[LastRenewedUtc] >= [AcquiredUtc] AND [ExpiresUtc] > [LastRenewedUtc]");

                            t.HasCheckConstraint("CK_JobLeases_WorkKind", "[WorkKind] IN ('DryRun','Execute')");

                            t.HasCheckConstraint("CK_JobLeases_WorkerNodeId", "[WorkerNodeId] <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobParameterEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerializedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId", "NormalizedName");

                    b.ToTable("JobParameters", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_JobParameters_PresentValue", "LEN(LTRIM(RTRIM([SerializedValue]))) > 0");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CollectedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("FencingToken")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("PowerShellExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("ScriptDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScriptVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<Guid>("WorkerNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId")
                        .IsUnique()
                        .HasDatabaseName("UX_JobReports_LeaseId");

                    b.HasIndex("PowerShellExecutionId")
                        .IsUnique()
                        .HasDatabaseName("UX_JobReports_PowerShellExecutionId");

                    b.HasIndex("WorkerNodeId");

                    b.HasIndex("ScriptDefinitionId", "ScriptVersionId");

                    b.HasIndex("JobId", "PackageId", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_JobReports_Job_Package_Schema");

                    b.HasIndex("ReportType", "CreatedUtc", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_JobReports_ReportType_CreatedUtc_Id");

                    b.ToTable("JobReports", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_JobReports_FencingToken", "[FencingToken] > 0");

                            t.HasCheckConstraint("CK_JobReports_Identifiers", "[Id] <> '00000000-0000-0000-0000-000000000000' AND [JobId] <> '00000000-0000-0000-0000-000000000000' AND [ScriptDefinitionId] <> '00000000-0000-0000-0000-000000000000' AND [ScriptVersionId] <> '00000000-0000-0000-0000-000000000000' AND [WorkerNodeId] <> '00000000-0000-0000-0000-000000000000' AND [LeaseId] <> '00000000-0000-0000-0000-000000000000' AND [PowerShellExecutionId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_JobReports_Sha256", "LEN([Sha256]) = 64 AND [Sha256] NOT LIKE '%[^0-9a-f]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_JobReports_SupportedType", "[PackageId] COLLATE Latin1_General_100_BIN2 = 'windows.local-host-inventory' AND [PackageVersion] COLLATE Latin1_General_100_BIN2 = '1.0.0' AND [ReportType] COLLATE Latin1_General_100_BIN2 = 'LocalHostInventory' AND [SchemaVersion] COLLATE Latin1_General_100_BIN2 = '1.0' AND [Format] COLLATE Latin1_General_100_BIN2 = 'Json'");

                            t.HasCheckConstraint("CK_JobReports_Timestamps", "[CollectedUtc] <= DATEADD(second, 5, [CreatedUtc])");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobTargetEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("JobId", "NormalizedName");

                    b.ToTable("JobTargets", "wsr");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.LocalHostInventoryReportEntity", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("OsArchitecture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("OsDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PowerShellVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ReportId");

                    b.ToTable("LocalHostInventoryReports", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_LocalHostInventoryReports_Architecture", "[OsArchitecture] COLLATE Latin1_General_100_BIN2 IN ('X86','X64','Arm','Arm64')");

                            t.HasCheckConstraint("CK_LocalHostInventoryReports_ComputerName", "LEN([ComputerName]) BETWEEN 1 AND 63 AND [ComputerName] NOT LIKE '%[^A-Za-z0-9-]%' COLLATE Latin1_General_100_BIN2 AND [ComputerName] NOT LIKE '-%' AND [ComputerName] NOT LIKE '%-'");

                            t.HasCheckConstraint("CK_LocalHostInventoryReports_OsDescription", "LEN([OsDescription]) BETWEEN 1 AND 256");

                            t.HasCheckConstraint("CK_LocalHostInventoryReports_ReportId", "[ReportId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_LocalHostInventoryReports_Versions", "LEN([OsVersion]) BETWEEN 5 AND 32 AND LEN([PowerShellVersion]) BETWEEN 5 AND 32 AND [OsVersion] NOT LIKE '%[^0-9.]%' AND [PowerShellVersion] NOT LIKE '%[^0-9.]%' AND [OsVersion] NOT LIKE '.%' AND [OsVersion] NOT LIKE '%.' AND [PowerShellVersion] NOT LIKE '.%' AND [PowerShellVersion] NOT LIKE '%.' AND [OsVersion] NOT LIKE '%..%' AND [PowerShellVersion] NOT LIKE '%..%'");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_ScriptDefinitions_NormalizedName");

                    b.ToTable("ScriptDefinitions", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_ScriptDefinitions_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ScriptDefinitions_RiskLevel", "[RiskLevel] IN ('ReadOnly','Low','Medium','High','Critical')");

                            t.HasCheckConstraint("CK_ScriptDefinitions_Timestamps", "[CreatedUtc] <= [UpdatedUtc]");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptParameterAllowedValueEntity", b =>
                {
                    b.Property<Guid>("ScriptParameterDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ScriptParameterDefinitionId", "NormalizedValue");

                    b.ToTable("ScriptParameterAllowedValues", "wsr");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptParameterDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ScriptVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScriptVersionId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_ScriptParameterDefinitions_Version_NormalizedName");

                    b.ToTable("ScriptParameterDefinitions", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_ScriptParameterDefinitions_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ScriptParameterDefinitions_SecureReference", "[ParameterType] <> 'SecureReference' OR [IsSensitive] = 1");

                            t.HasCheckConstraint("CK_ScriptParameterDefinitions_SensitiveDefault", "[IsSensitive] = 0 OR [DefaultValue] IS NULL");

                            t.HasCheckConstraint("CK_ScriptParameterDefinitions_Type", "[ParameterType] IN ('String','StringArray','Integer','Boolean','DateTime','Enum','SecureReference')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("DefaultTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<string>("GitCommitSha")
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("Major")
                        .HasColumnType("int");

                    b.Property<string>("MinimumPowerShellVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Minor")
                        .HasColumnType("int");

                    b.Property<int>("Patch")
                        .HasColumnType("int");

                    b.Property<string>("RelativeScriptPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ScriptDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScriptDefinitionId", "Id")
                        .HasName("AK_ScriptVersions_ScriptDefinitionId_Id");

                    b.HasIndex("ScriptDefinitionId", "Major", "Minor", "Patch")
                        .IsUnique()
                        .HasDatabaseName("UX_ScriptVersions_Definition_SemanticVersion");

                    b.ToTable("ScriptVersions", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_ScriptVersions_GitCommitSha", "[GitCommitSha] IS NULL OR (LEN([GitCommitSha]) BETWEEN 7 AND 64 AND [GitCommitSha] NOT LIKE '%[^0-9a-f]%' COLLATE Latin1_General_100_BIN2)");

                            t.HasCheckConstraint("CK_ScriptVersions_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ScriptVersions_Sha256", "LEN([Sha256]) = 64 AND [Sha256] NOT LIKE '%[^0-9a-f]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_ScriptVersions_Timeout", "[DefaultTimeoutMinutes] BETWEEN 1 AND 480");

                            t.HasCheckConstraint("CK_ScriptVersions_Version", "[Major] >= 0 AND [Minor] >= 0 AND [Patch] >= 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionPhaseEntity", b =>
                {
                    b.Property<Guid>("ScriptVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phase")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ScriptVersionId", "Phase");

                    b.ToTable("ScriptVersionPhases", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_ScriptVersionPhases_Phase", "[Phase] IN ('Discovery','Validation','DryRun','Report','Execute','PostValidation')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionReportFormatEntity", b =>
                {
                    b.Property<Guid>("ScriptVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportFormat")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ScriptVersionId", "ReportFormat");

                    b.ToTable("ScriptVersionReportFormats", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_ScriptVersionReportFormats_Format", "[ReportFormat] IN ('Text','Csv','Json','Html')");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerCapabilityEntity", b =>
                {
                    b.Property<Guid>("WorkerNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("WorkerNodeId", "NormalizedName");

                    b.ToTable("WorkerCapabilities", "wsr");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerNodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("RegisteredUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_WorkerNodes_IsEnabled");

                    b.HasIndex("LastHeartbeatUtc")
                        .HasDatabaseName("IX_WorkerNodes_LastHeartbeatUtc");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkerNodes_NormalizedName");

                    b.ToTable("WorkerNodes", "wsr", t =>
                        {
                            t.HasCheckConstraint("CK_WorkerNodes_Heartbeat", "[LastHeartbeatUtc] IS NULL OR [LastHeartbeatUtc] >= [RegisteredUtc]");

                            t.HasCheckConstraint("CK_WorkerNodes_Id", "[Id] <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.AuditEventPropertyEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.AuditEventEntity", "AuditEvent")
                        .WithMany("Properties")
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobApprovalEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("Approvals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("ScriptDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("ScriptDefinitionId", "ScriptVersionId")
                        .HasPrincipalKey("ScriptDefinitionId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobExecutionEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("Executions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerNodeEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkerNodeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobLeaseEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithOne("Lease")
                        .HasForeignKey("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobLeaseEntity", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerNodeEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkerNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobParameterEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("Parameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobReportEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptDefinitionEntity", "ScriptDefinition")
                        .WithMany()
                        .HasForeignKey("ScriptDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerNodeEntity", "WorkerNode")
                        .WithMany()
                        .HasForeignKey("WorkerNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", "ScriptVersion")
                        .WithMany()
                        .HasForeignKey("ScriptDefinitionId", "ScriptVersionId")
                        .HasPrincipalKey("ScriptDefinitionId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("ScriptDefinition");

                    b.Navigation("ScriptVersion");

                    b.Navigation("WorkerNode");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobTargetEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("Targets")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.LocalHostInventoryReportEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobReportEntity", "Report")
                        .WithOne("Inventory")
                        .HasForeignKey("WindowsScriptRunner.Infrastructure.Persistence.Entities.LocalHostInventoryReportEntity", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptParameterAllowedValueEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptParameterDefinitionEntity", "ScriptParameterDefinition")
                        .WithMany("AllowedValues")
                        .HasForeignKey("ScriptParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScriptParameterDefinition");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptParameterDefinitionEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", "ScriptVersion")
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("ScriptVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScriptVersion");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptDefinitionEntity", "ScriptDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("ScriptDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScriptDefinition");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionPhaseEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", "ScriptVersion")
                        .WithMany("SupportedPhases")
                        .HasForeignKey("ScriptVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScriptVersion");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionReportFormatEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", "ScriptVersion")
                        .WithMany("SupportedReportFormats")
                        .HasForeignKey("ScriptVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScriptVersion");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerCapabilityEntity", b =>
                {
                    b.HasOne("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerNodeEntity", "WorkerNode")
                        .WithMany("Capabilities")
                        .HasForeignKey("WorkerNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkerNode");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Executions");

                    b.Navigation("Lease");

                    b.Navigation("Parameters");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.JobReportEntity", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptDefinitionEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptParameterDefinitionEntity", b =>
                {
                    b.Navigation("AllowedValues");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.ScriptVersionEntity", b =>
                {
                    b.Navigation("ParameterDefinitions");

                    b.Navigation("SupportedPhases");

                    b.Navigation("SupportedReportFormats");
                });

            modelBuilder.Entity("WindowsScriptRunner.Infrastructure.Persistence.Entities.WorkerNodeEntity", b =>
                {
                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
